<?php
// Initiate connection to database and user login session
include("include/session.php");

// Set values for page
$page_title = "History of Alpha Kappa Chapter";
$current_page = "about";

// Load header
include_once("include/header.php");

// Below this PHP block, set page-specific JavaScript, CSS, and anything else for the <head>
##################################################
?>

<?php
##################################################
// Load top navigation
include_once("include/topnav.php");

// Below this PHP block, enter only the main HTML content of the page. All necessary layout, body, html, etc. tags are included in the PHP includes.
##################################################
?>
			<h2>History of Alpha Kappa Chapter</h2>
			<p>The Alpha Kappa Chapter of Alpha Phi Omega has a long and distinguished history stretching back to the 1930s. Learn more about where we come from and where we plan to go.</p>
<h3>Beginnings</h3>
			<p>Alpha Kappa became the second chapter in Los Angeles when it was founded in 1934 at the University of Southern California. The chapter's activation and first Initiation Ceremony were held on June 3, 1934. Its founding was sponsored by Theodore R. Pfalsgraf, Assistant Scout Executive of the <a href="http://www.boyscoutsla.org/" rel="external">Los Angeles Area Council</a> of the <a href="http://scouting.org/" rel="external">Boy Scouts of America</a>. The founding student was Nils O. Althin, a doctoral candidate in physical education from Sweden; the founding group included twenty-seven undergraduates, three faculty advisors, one Scouting advisor, and five honorary members. The first chapter president was Everett Winn.</p>
			<p>According to records at the Alpha Phi Omega National Office, the chapter was dormant during 1943-1948, due to World War II, and again from 1958-1967. Since the national Board of Directors never formally declared the chapter inactive, a formal reactivation was not necessary following these years of inactivity. The chapter simply initiated a new pledge class. In the spring of 1967, Bob Biggers and Larry Fowler of USC met with Alpha Phi Omega representative David Harris and Dean of Student Affairs Mulvey White. They decided to re-establish Alpha Kappa Chapter at USC. Officers of the group that semester were President Larry Fowler, Secretaries Gabe Robles and Mike Miles, Treasurer Ron Prince, and Rush Chairman Tim Huntley. The chapter advisors were Head Football Coach John McKay, university Presbyterian pastor Marylnn May, Assistant Dean of Men Patrick Ryan, English instructor Robert Christmas, Arthur Dolder of the Boy Scouts of America Los Angeles Area Council, and Mulvey White.</p>
<h3>Radical Changes</h3>
			<p>The Spring 1967 pledge class performed service in many areas including creating a recreation program at John Adams Junior High School, a commuter Share-A-Ride center on campus, and a tutoring program at <a href="http://www.mahs.org/" rel="external">Manual Arts High School</a>. The new group's first official recruitment in the fall of 1967 involved a radically different new-member program. These changes included the elimination of the pledge period. Open meetings were held where potential members would hear speakers describe the Fraternity, meet members, and see special entertainment. Three orientation meetings were then held where individuals could declare their intent to join the Fraternity. Later, the active members would review the initiates' mastery of knowledge of the Fraternity. The total time from orientation to initiation was less than one month.</p>
<h3>Membership Decline</h3>
			<p>Its experimentation over, the chapter  adopted the traditional recruitment and pledge programs in the 1970s. Although highly visible on campus during these years, the chapter's membership declined for Alpha Phi Omega, as it did nationally for all Greek organizations during the 1970s, until no member remained in 1976. The chapter was officially declared inactive in January 1980. In 1988, David Moll (Iota Phi, &lsquo;84-<abbr title="University of California, Davis">UC Davis</abbr>), a pharmacology graduate student, held meetings on campus, with the assistance of Section 1 staff members Jeff Schwartz and Mark Saigon, to reactivate the old Alpha Kappa Chapter. The group rechartered on October 28, 1989, and hosted the Section 1 Conference that same weekend. The chapter-founding group included fifteen members, three faculty advisors, and three Scouting advisors. The first president of the rechartered chapter was Glen Espino. The Ceremony was conducted by Rho Gamma Chapter, with Irwin Gerst and Earle Herbert from the national Board of Directors. Mark Sugino was Section 1 Chair. For his efforts, David Moll was awarded the Ellsworth S. Dobson Award for Membership Efforts by the Board of Directors.</p>
			<p>Over the years, membership again declined. At the beginning of the 1992-1993 school year, Howard Mora (Lambda Nu, &lsquo;88-Duke University), a graduate student in biomedical engineering, came to find Alpha Kappa Chapter active, but with zero members. With support from Chapter Advisor Rhonda Aven, Section 1 staff members Mark Sugino and Matthew Troth, and a loan of materials from other chapters, namely <a href="http://www.csupomona.edu/" rel="external">Cal Poly Pomona</a>, Mora oversaw the chapter until a new pledge class of ten members could be initiated. Past National President Earle Herbert was present at the induction ceremony. A successful Spring &lsquo;93 pledge class, which included Betsy Farrington, who would eventually become chapter president and oversee much of the early growth, was also run by Mora, and Alpha Kappa proudly hosted the fall Section 1 Leadership Conference that year. Due to a large portion of the active members graduating and internal problems, membership once again declined.</p>
<h3>New Beginnings</h3>
			<p>At that time, Mora moved into a role in the Section 1 staff under Matthew Troth. Weakened, Alpha Kappa Chapter slowly diminished with few initiates each semester. With the efforts of the actives, a successful Fall &lsquo;94 recruitment was able to double the membership. In the Spring of &lsquo;95, Mora was the pledge class namesake and was later awarded the <a href="http://www.apo.org/show/About_Us/Awards/Chapter/Chapter_DSK/" rel="external">Chapter Distinguished Service Key</a>. In the Fall of &lsquo;96, a great recruitment brought in 28 new pledges, making Alpha Kappa Chapter 45 brothers strong. However, once again plagued with internal struggles and graduating brothers, membership remained small with no recruitment period during the Fall &lsquo;97 semester.</p>
			<p>In 2005, Alpha Kappa received a <a href="http://www.apo.org/show/About_Us/Awards/Chapter/Chapter_of_Excellence/" rel="external">Chapter of Excellence (COE) Award</a> from the National Office in recognition of the chapter's "well-rounded program that includes not only the required elements, but also good chapter programs in the areas of development and service." Alpha Phi Omega experienced yet another small pledge class in Spring &lsquo;08. But some internal changes, like that in the family structure, helped fuel competition, spirit, and thus interest in Alpha Phi Omega. The chapter originally had three families: Alpha, Phi, and Omega, with Alpha as the largest and Omega the smallest with merely five members. The disproportionate family sizes eventually led to the combining of the Phi and Omega families into a new Kappa family, which created a new rivalry between the Alpha and Kappa families through family competitions; these fun and friendly contests encouraged teamwork and unity within a family. This change, as well as other factors, like an amazing Fall &lsquo;08 Rho class with over 40 pledges—more than 30 of whom crossed, led to one of the largest pledge turnouts in chapter history.</p>
<h3>Recent Developments</h3>
			<p>Following the upward trend, the Spring &lsquo;09 Sigma and Fall &lsquo;09 Tau pledge classes also boasted more than 40 pledges each. At that time, Kappa was the largest family and won the two family competitions during the two-family period. Due to the growth of the chapter, efforts were made to reorganize the two-family system back into the original three-family structure; while Alpha retained its family members, Kappa was divided between the newly reinstated Phi and Omega families.</p>
			<p>In 2008, and again in 2009, Alpha Kappa Chapter won the "Most Spirited Organization Award" at USC's annual Tommy Awards; also in 2009, the chapter took home the "Best Service Organization Award." In Spring 2010, Alpha Kappa Chapter hosted the Section 1 Leadership Conference, which was themed "<abbr title="Crime Scene Investivation">CSI</abbr>: USC."</p>
			<p>Despite historically low membership, the strong pledge classes of recent years signal a positive change for the Fraternity as it forges a new identity on USC's campus.</p>
<?php
##################################################
// Load sidebar, footer, and dropdown stats panel
include_once("include/sidebarFooterDropdownpanel.php");
?>